name: Android CI/CD

on:
  push:
    branches:
      - v4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Debug APK
        run: ./gradlew assembleDebug  

      - name: Install Tree
        run: sudo apt-get install tree

      - name: Print Folder Structure
        run: tree -d

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute ./app/build/outputs/apk/debug/app-debug.apk --app 1:481720887348:android:dc082c38bf6312ac774261 --groups sampleAppTesters
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
